<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260823000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Aligns the statistics identifier with Doctrine PostgreSQL identity mapping.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE request_statistics ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE request_statistics ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE request_statistics ALTER id DROP IDENTITY');
        $this->addSql("ALTER TABLE request_statistics ALTER id SET DEFAULT nextval('request_statistics_id_seq'::regclass)");
    }
}
